//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_customerOrdersDetails
    {
        public int orderid { get; set; }
        public Nullable<System.DateTime> orderdate { get; set; }
        public string customerid { get; set; }
        public string CompanyName { get; set; }
        public short Quantity { get; set; }
        public decimal UnitPrice { get; set; }
        public float Discount { get; set; }
        public Nullable<int> ShipVia { get; set; }
        public string ShipName { get; set; }
        public Nullable<System.DateTime> ShippedDate { get; set; }
    }
}
